#ifndef COMMANDS
#define COMMANDS

/*主机可以向从机发送的命令码*/
#define SSP_CMD_RESET						0x01
#define SSP_CMD_SET_INHIBITS				0x02
#define SSP_CMD_DISPLAY_ON					0x03
#define SSP_CMD_DISPLAY_OFF					0x04
#define SSP_CMD_SETUP_REQUEST				0x05
#define SSP_CMD_HOST_PROTOCOL_VERSION		0x06
#define SSP_CMD_POLL						0x07
#define SSP_CMD_REJECT_BANKNOTE				0x08
#define SSP_CMD_DISABLE						0x09
#define SSP_CMD_ENABLE						0x0A
#define SSP_CMD_PROGRAM_FIRMWARE			0X0B
#define SSP_CMD_GET_SERIAL_NUMBER			0x0C
#define SSP_CMD_UNIT_DATA					0x0D
#define SSP_CMD_CHANNEL_VAL_REQUEST			0x0E
#define SSP_CMD_CHANNEL_SECURITY_DATA		0x0F
#define SSP_CMD_CHANNEL_RE_TEACH_DATA		0x10
#define SSP_CMD_SYNC						0x11
#define SSP_CMD_LAST_REJECT_CODE			0x17
#define SSP_CMD_HOLD						0x18
#define SSP_CMD_GET_FIRMWARE_VERSION		0x20
#define SSP_CMD_GET_DATASET_VERSION			0x21
#define SSP_CMD_GET_BAR_CODE_READER_CONF	0x23
#define SSP_CMD_SET_BAR_CODE_READER_CONF	0x24
#define SSP_CMD_GET_BAR_CODE_INHIBIT_STAT	0x25
#define SSP_CMD_SET_BAR_CODE_INHIBIT_STAT	0x26
#define SSP_CMD_GET_BAR_CODE_DATA			0x27
#define SSP_CMD_SET_GENERATOR				0x4A
#define SSP_CMD_SET_MODULUS					0x4B
#define SSP_CMD_KEY_EXCHANGE				0x4C
#define SSP_CMD_POLL_WITH_ACK				0x56
#define SSP_CMD_EVENT_ACK					0x57
#define SSP_CMD_GET_COUNTERS				0x58
#define SSP_CMD_RESET_COUNTERS				0x59
//自定义
#define SSP_CMD_HEADER						0xD1
#define SSP_CMD_RAMBLOCKS					0xD2
#define SSP_CMD_UPDATECODE					0XD3
#define SSP_CMD_RESENDHEADER				0XD4
#define SSP_CMD_TRANSFEREACHBLOCK			0XD5


/*poll命令的应答码，表明读出来的纸币器的状态*/
#define SSP_RESPONSE_CMD_OK					0xF0
#define SSP_POLL_RESET						0xF1
#define SSP_POLL_NOTE_READ					0xEF
#define SSP_POLL_CREDIT						0xEE
#define SSP_POLL_REJECTING					0xED
#define SSP_POLL_REJECTED					0xEC
#define SSP_POLL_STACKING					0xCC
#define SSP_POLL_STACKED					0xEB
#define SSP_POLL_SAFE_JAM					0xEA
#define SSP_POLL_UNSAFE_JAM					0xE9
#define SSP_POLL_DISABLED					0xE8
#define SSP_POLL_FRAUD_ATTEMPT				0xE6
#define SSP_POLL_STACKER_FULL				0xE7
#define SSP_POLL_NOTE_CLEARED_FROM_FRONT	0xE1
#define SSP_POLL_NOTE_CLEARED_TO_CASHBOX	0xE2
#define SSP_POLL_CHANNEL_DISABLE			0xB5
#define SSP_POLL_INITIALISING				0xB6


/*主机可以向从机接收的命令码*/
#define SSP_RESPONSE_CMD_UNKNOWN			0xF2
#define SSP_RESPONSE_CMD_WRONG_PARAMS		0xF3
#define SSP_RESPONSE_CMD_PARAM_OUT_OF_RANGE 0xF4
#define SSP_RESPONSE_CMD_CANNOT_PROCESS		0xF5
#define SSP_RESPONSE_CMD_SOFTWARE_ERROR		0xF6
#define SSP_RESPONSE_CMD_FAIL				0xF8
#define SSP_RESPONSE_CMD_KEY_NOT_SET		0xFA

#endif